/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.dii.oop;

import org.dii.oop.lesson01.exercise03.Lesson;

public class App {
    public static void main(String[] args) {
        Lesson exercise = new Lesson();
        exercise.start();
    }
}
